---

- hosts: all
  become: true
  tasks:

  - name: Update Repo & Install apache2, php..
    package:
      update_cache: yes
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
