---

- hosts: all
  become: true
  tasks:

  - name: remove package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove package (Rocky)
    dnf:
      name:
        - httpd
        - php
        - mariadb
    when: ansible_distribution == "Rocky"

